export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_USERINFO: "SET_USERINFO",
  SET_PLAYLIST_DATA: "SET_PLAYLIST_DATA",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
  SET_SEARCH_DATA: "SET_SEARCH_DATA",
  SET_RELEASE_DATA: "SET_RELEASE_DATA",
  SET_TOP_DATA: "SET_TOP_DATA",
  SET_CURRENT_DATA: "SET_CURRENT_DATA",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_CLIENT_ID: "SET_CLIENT_ID",
  SET_ALERT:"SET_ALERT"
};
